<a href="https://colab.research.google.com/github/khushiyadav03/Machine-Learning/blob/main/Working_with_Matrix_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Creating a Matrix using Numpy

In [2]:
matrix_1 = np.array([[2,3], [6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [3]:
matrix_1.shape

(2, 2)

In [4]:
matrix_2 = np.array([[10,35,45], [50,64,80], [20,15,90]])
print(matrix_2)

[[10 35 45]
 [50 64 80]
 [20 15 90]]


In [5]:
matrix_2.shape

(3, 3)

Creating Matrices with Random Values

In [6]:
random_matrix = np.random.rand(3, 3)
print(random_matrix)

[[0.22188224 0.80477258 0.02337704]
 [0.32439996 0.05135237 0.72263596]
 [0.22880844 0.12683358 0.49240043]]


In [7]:
# creating matrix with random int
random_int_matrix = np.random.randint(100, size=(4, 5))
print(random_int_matrix)

[[12 90 85 11 34]
 [64 74 69 16 11]
 [22 76 64 85 63]
 [52 13 89 34 53]]


Matrix with all the values as 1

In [9]:
matrix_3 = np.ones((2, 3))
print(matrix_3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [10]:
matrix_3 = np.ones((2,3), dtype=int)
print(matrix_3)

[[1 1 1]
 [1 1 1]]


In [11]:
matrix_3 = np.ones((10,10), dtype=int)
print(matrix_3)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


Null Matrix or Zero Matrix

In [12]:
null_matrix = np.zeros((3, 4))
print(null_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
null_matrix = np.zeros((3, 4), dtype=int)
print(null_matrix)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


Identity Matrix

In [14]:
identity_matrix = np.eye(3, 3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
identity_matrix = np.eye(5, 5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Transpose of a Matrix

In [17]:
# matrix with random integer values
a = np.random.randint(100, size=(4, 5))
print(a)

[[90 75 66 43 72]
 [12 13 48 80  9]
 [82 70 14 12 84]
 [82 28  4  3 45]]


In [18]:
transpose_of_a = np.transpose(a)
print(transpose_of_a)

[[90 12 82 82]
 [75 13 70 28]
 [66 48 14  4]
 [43 80 12  3]
 [72  9 84 45]]
