<a href="https://colab.research.google.com/github/khushiyadav03/Machine-Learning/blob/main/Matrix_Operations_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

**Matrix Addition**

Two Matrices can be added only if they have the same shape

In [2]:
# creating two matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [3]:
print(A)

[[1 2]
 [3 4]]


In [4]:
print(B)

[[5 6]
 [7 8]]


In [5]:
A.shape

(2, 2)

In [6]:
B.shape

(2, 2)

Adding two Matrices

In [7]:
sum = A + B

In [8]:
print(sum)

[[ 6  8]
 [10 12]]


In [9]:
# creating two matrices with random values
mat_1 = np.random.randint(10, size=(3, 3))
mat_2 = np.random.randint(10, size=(3, 3))

In [10]:
print(mat_1)

[[1 5 7]
 [4 6 3]
 [0 7 2]]


In [11]:
print(mat_2)

[[5 0 9]
 [1 0 4]
 [8 5 5]]


In [12]:
sum = np.add(mat_1, mat_2)

In [13]:
print(sum)

[[ 6  5 16]
 [ 5  6  7]
 [ 8 12  7]]


In [14]:
# create two matrices with random valyes
mat_3 = np.random.randint(10, size=(3, 3))
mat_4 = np.random.randint(10, size=(3, 4))

sum_2 = np.add(mat_3, mat_4)

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

We get this error because shape of matrix_3 and matrix_4 are different

**Matrix Subtraction**

In [15]:
# creating two matrices
A = np.array([[2, 3], [4, 5]])
B = np.array([[6, 7], [8, 9]])

In [16]:
print(A)

[[2 3]
 [4 5]]


In [17]:
print(B)

[[6 7]
 [8 9]]


In [18]:
diff = A - B

print(diff)

[[-4 -4]
 [-4 -4]]


In [19]:
# create two matrices with random values
matrix_1 = np.random.randint(10, size=(3,3))
matrix_2 = np.random.randint(20, size=(3,3))

In [20]:
print(matrix_1)

[[9 7 0]
 [2 8 1]
 [5 9 0]]


In [21]:
print(matrix_2)

[[12 17 10]
 [13 19 10]
 [ 7 15 10]]


In [23]:
diff = np.subtract(matrix_1, matrix_2)

print(diff)

[[ -3 -10 -10]
 [-11 -11  -9]
 [ -2  -6 -10]]


**Multiplying a matrix by a scalar**

In [24]:
x = 5
y = np.random.randint(10, size=(3,3))

In [25]:
print(y)

[[3 6 4]
 [0 3 3]
 [7 7 4]]


In [26]:
product = np.multiply(x, y)

print(product)

[[15 30 20]
 [ 0 15 15]
 [35 35 20]]


**Multiplying 2 Matrices**

In [31]:
# create two matrices with random values/
mat_3 = np.random.randint(10, size=(3,3))
mat_4 = np.random.randint(10, size=(3,4))

In [32]:
print(mat_3)

[[4 0 5]
 [5 5 7]
 [3 6 4]]


In [33]:
print(mat_4)

[[4 6 3 0]
 [5 2 2 2]
 [0 5 7 3]]


In [34]:
product = np.dot(mat_3, mat_4)

print(product)

[[16 49 47 15]
 [45 75 74 31]
 [42 50 49 24]]


In [35]:
product.shape

(3, 4)

**Element wise Matrix Multiplication**

In [36]:
# create two matrices waith random values
mat_3 = np.random.randint(5, size=(3,3))
mat_4 = np.random.randint(5, size=(3,3))

In [37]:
print(mat_3)

[[3 4 0]
 [3 4 2]
 [3 2 1]]


In [38]:
print(mat_4)

[[0 1 4]
 [4 0 4]
 [0 2 1]]


In [39]:
product = np.multiply(mat_3, mat_4)

print(product)

[[ 0  4  0]
 [12  0  8]
 [ 0  4  1]]


In [40]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,4))

In [41]:
product = np.multiply(matrix_3, matrix_4)

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

Hum np.dot use karte hain matrix multiplication ke liye. Iske liye pehle matrix ke columns ki sankhya doosre matrix ke rows ki sankhya ke barabar honi chahiye. Shapes alag ho sakte hain agar yeh condition poori ho. Hum np.multiply use karte hain element-wise multiplication ke liye, jismein dono matrices ka shape bilkul same hona chahiye.